apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ticketmaster-ingress
spec:
  entryPoints:
    - web
  routes:
    #  LOGIN (Publikus)
    # Bárki elérheti, hogy tokent szerezzen
    - match: PathPrefix(`/api/Auth`)
      kind: Rule
      services:
        - name: auth-service
          port: 8080

    # CATALOG LISTÁZÁS
    - match: PathPrefix(`/api/Events`) 
      kind: Rule
      middlewares:
        - name: jwt-auth
      services:
        - name: catalog-service
          port: 8080

    #  BOOKING
    - match: PathPrefix(`/api/Booking`)
      kind: Rule
      middlewares:
        - name: jwt-auth
      services:
        - name: booking-service
          port: 8080